### ISSUE TITLE
bug in simple_python: installing skeletor twice

### ISSUE THREAD

**Issue by dpacheco0921** [natverse/fafbseg#135]
In line 22-25 of function simple_python it says:

```
message("Installing meshparty (includes Seung lab mesh skeletonisation)")
ourpip("skeletor")
message("Installing skeletor (Philipp Schlegel mesh skeletonisation)")
ourpip("skeletor")
```

Should line 23 be?

`ourpip("meshparty")`

**Comment by jefferis** [comment]
Thanks a lot for spotting this @dpacheco0921! You are quite right of course although the fact that this has gone unnoticed for a while is a clue that we are not using Meshparty at the moment ...
