### ISSUE TITLE
Move fafbseg to natverse

### ISSUE THREAD

**Issue by jefferis** [natverse/fafbseg#19]
* It's probably getting stable and useful enough. 
- [x] actually do the move on github!
- [x] but still probably needs experimental badge
- [x] fix URLs referencing `jefferis/fafbseg`
- [x] may need to run nat.devtools::nat_check_urls()
- [x] and nat.devtools::nat_setup_package()
- [x] potentially redirect github pages like this https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by jefferis** [comment]
@SridharJagannathan are you working on this already?

**Comment by jefferis** [comment]
I've just made some of the changes on master as per check boxes, so be sure to pull!

**Comment by SridharJagannathan** [comment]
@jefferis : 
1. I have tried to update most of the stuff from `nat.devtools::nat_setup_package()`, however it seems when running the `usethis::use_package_doc()` it overwrites the existing `fafbseg-package.R` file and hence I avoided that and used the `devtools::document()` directly.
2. Further, I updated travis for fixing some warnings and added a first pass code coverage from coverall.

**Comment by jefferis** [comment]
Thanks for the redirect instructions @SridharJagannathan! I've followed them, I think, but I don't see anything yet. I've given you access to the repo, so perhaps you can check in and see if all looks ok. It would be great to do the same for **nat** as well.

**Comment by SridharJagannathan** [comment]
@jefferis sorry, I forgot to mention you need a `index` file to the serve the site, I have fixed the same and have also added redirects for `nat` as well. Once it is Ok, then you can close this issue.
btw it seems in the site http://natverse.org/nat/ the `nature 2011` paper pic is failing to render?

**Comment by jefferis** [comment]
Great working now for me after your updates to https://github.com/jefferis/jefferis.github.io best, G.
