### ISSUE TITLE
Adapt to breaking changes in fafbseg-py

### ISSUE THREAD

**Issue by jefferis** [natverse/fafbseg#193]
Inc l2 skels. See https://github.com/navis-org/fafbseg-py/blob/master/changelog.md

**Comment by schlegelp** [comment]
Was about to open an issue myself but you got there first.

**Comment by jefferis** [comment]
@schlegelp how do I authenticate fafbseg$flywire now that the default is to use the public dataset only?

**Comment by jefferis** [comment]
I think I can do something like:
```py
fp.flywire.set_default_dataset('flywire_fafb_production')
```
to choose the production dataset and it should pick up the auth token from the standard location.

**Comment by schlegelp** [comment]
Yes, that will set the default dataset for the session. You can also pass a `dataset=''production"` parameter directly to the respective functions.

**Comment by jefferis** [comment]
closed by #194
